### ISSUE TITLE
Importing this library generated import errors and crashed 1.0.2

### ISSUE THREAD

**Issue by DaveHineman** [Adr-hyng/74LS-Series-Fritzing-Parts#1]
To recreate:
macOS Sonoma, Intel Processor, Fritzing 1.0.2. Select Import from Parts menu, choose this 74LSxxx.fzbz file and many of these errors appear. After dismissing the errors, Fritzing crashes. After restarting Fritzing, the library has not been imported.

Parse error (2) at line 30, column 30:
Unexpected ''.
/Users/davidhineman/Documents/Fritzing/parts/contrib/74LS139_caeedddb87cfcc284ead6e3ab977244f_2.fzp

**Comment by buccaneeruk** [comment]
I can confirm this crashing issue although it wants to place the items in a users fritzing folder in documents, it is trying to locate them from a user named Adrian's documents folder see attached image
![Screenshot 2024-03-27 100145](https://github.com/Adr-hyng/74LS-Series-Fritzing-Parts/assets/54948861/68651370-dcb8-4ac2-9860-3b4b521afecf)

**Comment by microplayer** [comment]
MacOS Sonoma on M1 running Fritzing 1.0.2. Same experience as above.
The error message is a bit different - sorry, running my Mac in german:

Der XML-Code für Teil /Users/<username>/Documents/Fritzing/parts/contrib/74LS139_caeedddb87cfcc284ead6e3ab977244f_2.fzp
enthält einen Fehler (2) bei Zeile 30, Spalte 30:
Unerwartet ''.

This repeats for 8 items, then this message appears (see also buccaneeruk):
Die folgenden 8 Bauteile konnten nicht gefunden werden:

'74LS93_a096787a5bde07a5c3059fbc630d9af8_4'
bei
'C:/Users/Adrian/Documents/Fritzing/parts/user/74LS93_a096787a5bde07a5c3059fbc630d9af8_4.fzp'
'74LS73_46d72ba79b041542f45f38c1982d0668_2'
bei
'C:/Users/Adrian/Documents/Fritzing/parts/user/74LS73_46d72ba79b041542f45f38c1982d0668_2.fzp'
'AT28C16_ee1ea850737774faa6dfc445141b08b0_3'
bei
'C:/Users/Adrian/Documents/Fritzing/parts/user/AT28C16_ee1ea850737774faa6dfc445141b08b0_3.fzp'
'74LS645_412cd614f9e6f8809a066dc9285d5568_2'
bei
'C:/Users/Adrian/Documents/Fritzing/parts/user/74LS645_412cd614f9e6f8809a066dc9285d5568_2.fzp'
'AT28C64_200de5d41ea251fbf2f676512cd05f18_2'
bei
'C:/Users/Adrian/Documents/Fritzing/parts/user/AT28C64_200de5d41ea251fbf2f676512cd05f18_2.fzp'
'74LS95_38e6dc653c95572ef4390eb238211269_3'
bei
'C:/Users/Adrian/Documents/Fritzing/parts/user/74LS95_38e6dc653c95572ef4390eb238211269_3.fzp'
'74LS151_6ae68dfa6e9d1e69a2cd878a994abade_2'
bei
'C:/Users/Adrian/Documents/Fritzing/parts/user/74LS151_6ae68dfa6e9d1e69a2cd878a994abade_2.fzp'
'74LS139_caeedddb87cfcc284ead6e3ab977244f_2'
bei
'C:/Users/Adrian/Documents/Fritzing/parts/user/74LS139_caeedddb87cfcc284ead6e3ab977244f_2.fzp'

Hitting OK finally crashes Fritzing :-(

Good luck hunting this bug!

**Comment by Adr-hyng** [comment]
Sorry it took long to respond, but currently I don't have access to 1.0.0+ above fritzing application version. And I'm also new to fritzing part creation. This also occurred when I was importing this fritzing parts bin into a new device.

My temporary solution for this is just download the Fritzing Breadboard [`Main.fzz`](https://github.com/Adr-hyng/74LS-Series-Fritzing-Parts/blob/main/Main.fzz) file instead of the fritzing parts. It accessed all of the 74LSxxx created, and modified by me.
If you want to import any Logic ICs you need, just export the selected part from `Main.fzz` circuit breadboard file, and import it into your project's fritzing parts. 

Hope it helped, Regards.
Adrian
